name: my frist workflow

on: push

jobs:
    frist_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome-meassage
          run: echo "my frist job"

        - name: list files
          run: ls

        - name: read file
          run: cat README.md
